name: time_track_cli
description: >-
  A simple command-line time tracking application 
  demonstrating usage of Realm Dart SDK

version: 0.3.0
homepage: https://github.com/realm/realm-dart

publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  domain:
    path: ../domain
  realm_dart: ^0.8.0+rc
  args: ^2.0.0
  dart_console: ^1.1.2

dev_dependencies:
  lints: ^2.0.0

#dependency_overrides:
#  realm_dart:
#    path: ../../../realm-dart  
