name: myapp
description: A simple command-line application using Realm Dart SDK.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  realm_dart: ^0.8.0+rc

dev_dependencies:
  lints: ^2.0.0
