name: CI new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Released new version of Realm (0.X.0+beta).
        required: true
        type: string

jobs:
   prepare-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update realm_dart in pubspec.yaml
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'realm_dart: .*'
          replace: 'realm_dart: ${{ inputs.version }}'
          include: '**pubspec.yaml'

      - name: Update realm in pubspec.yaml
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'realm: .*'
          replace: 'realm: ${{ inputs.version }}'
          include: '**pubspec.yaml'

      - name: Configure functions
        run: |
          ci.sh --get
          ci.sh --generate

      - name: Create Version Upgrade PR
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          branch: release/${{ inputs.version }}
          base: master
          title: '[Realm version upgrade ${{ inputs.version }}]'
          draft: false
          body: An automated PR for released realm version.
          commit-message: Update samples with realm ${{ inputs.version }}
          token: ${{ secrets.REALM_CI_PAT }}
